export default {
  home: {
    i18n: 'casino',
    theme: 'black',
    cardRatio: 'short',
    containerType: 'flex',
  },
  casino: {
    i18n: 'casino',
    theme: 'purple',
    cardRatio: 'short',
    containerType: 'flex',
  },
  sport: {
    i18n: 'sport',
    theme: 'green',
    cardRatio: 'short',
    containerType: 'grid',
  },
  slot: {
    i18n: 'slot',
    theme: 'navy',
    cardRatio: 'short',
    containerType: 'grid',
  },
  poker: {
    i18n: 'Poker',
    theme: 'gold',
    cardRatio: 'short',
    containerType: 'grid',
  },
  arcade: {
    i18n: 'arcade',
    theme: 'red',
    cardRatio: 'short',
    containerType: 'grid',
  },
  fishing: {
    i18n: 'fishing',
    icon: 'category/fish',
    theme: 'red',
    cardRatio: 'short',
    containerType: 'grid',
  },
  table: {
    i18n: 'table',
    icon: 'category/table',
    theme: 'red',
    cardRatio: 'short',
    containerType: 'grid',
  },
  crypto: {
    i18n: 'crypto',
    icon: 'category/crypto',
    theme: 'red',
    cardRatio: 'short',
    containerType: 'grid',
  },
  crash: {
    i18n: 'crash',
    icon: 'category/crash',
    theme: 'red',
    cardRatio: 'short',
    containerType: 'grid',
  },
  pvp: {
    i18n: 'pvp',
    icon: 'category/pvp',
    theme: 'red',
    cardRatio: 'short',
    containerType: 'grid',
  },
  demo: {
    i18n: 'demo',
    icon: 'demo',
    theme: 'black',
    cardRatio: 'short',
    containerType: 'grid',
  },
}
