export { usePayment } from './store/payment'
export { usePromotionData, usePromotion, getConditionsByEvidence } from './store/promotion'
export { useDefaultLangauge, useCurrencyCode } from './store/setting'
export { useProvider } from './store/provider'
export { useInformation } from './store/information'
