export { usePayment } from './store/payment'
export { usePromotionData, usePromotion, getConditionsByEvidence } from './store/promotion'
export { useProvider } from './store/provider'
export { useInformation } from './store/information'
export { useGame, useLaunchGame } from './store/game'
